name = "dsvi-email-functions"
compatibility_date = "2024-03-08"
compatibility_flags = ["nodejs_compat"]

[vars]
BREVO_API_KEY = "YOUR_BREVO_API_KEY_HERE"
BREVO_SMTP_USERNAME = "YOUR_SMTP_USERNAME_HERE"
BREVO_SMTP_PASSWORD = "YOUR_SMTP_PASSWORD_HERE"
VITE_SUPABASE_URL = "https://rzfilfpjxfinxxfldzuv.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6ZmlsZnBqeGZpbnh4ZmxkenV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjA0NzMsImV4cCI6MjA2Mzg5NjQ3M30.6Wf8vIJ2Bo1QS0Ie_16xqHZQhCdfsXDmNATPLT3sAfg"
VITE_DEFAULT_RESEND_API_KEY = "re_6ayikHHF_JhrAdn6hK4iEPKCThk9vquJq"

[[pages]]
functions = "functions"
