name = "dsvi-email-functions"
compatibility_date = "2024-03-08"
compatibility_flags = ["nodejs_compat"]

[vars]
BREVO_API_KEY = "YOUR_BREVO_API_KEY_HERE"
BREVO_SMTP_USERNAME = "YOUR_SMTP_USERNAME_HERE"
BREVO_SMTP_PASSWORD = "YOUR_SMTP_PASSWORD_HERE"

[[pages]]
functions = "functions"
